# Cloudflare Pages Configuration
name = "ai-photo-editor"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
destination = "./"

[env.production.vars]
# Environment variables will be set in Cloudflare Pages dashboard
# HUGGING_FACE_TOKEN = "your_token_here"
# REPLICATE_TOKEN = "your_token_here" 
# REMOVEBG_TOKEN = "your_token_here"
# PHOTOROOM_TOKEN = "your_token_here"